name: dananer
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio:
  shared_preferences:
  flutter_bloc:
  bloc:
  flutter_onboard:
  fluttertoast: ^8.2.1
  conditional_builder_null_safety:
  carousel_slider: ^5.0.0
  buttons_tabbar: ^1.3.10
  sqflite:
  url_launcher:
  intl:
  image_picker:
  lottie: ^3.3.1
  http_parser: ^4.0.2
  top_snackbar_flutter: ^3.2.0
  flutter_fortune_wheel: ^1.3.2
  onesignal_flutter: ^5.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/items/
#    - assets/lottie/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo/static/Cairo-Bold.ttf

